name: 'Build push front image'
on:
  push:
    branches:
      - main

jobs:
  build-front-image:
    # needs: install-back-dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Use Build and Push Docker Image action
      uses: SIT-LightCode/LC-Deployment/actions/build-push-front@main
      with:
        image: "front-end"
        tags: "automated"
        type: "dev"
        ghcr_pat: ${{ secrets.GHCR_PAT }}