name: 'Build push front image'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag name
      type:
        description: 'type of image is stable or not-stable'
        required: true
        default: 'not-stable'
        type: choice
        options:
          - stable
          - not-stable


jobs:
  build-froint-image:
    # needs: install-back-dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Use Build and Push Docker Image action
      uses: SIT-LightCode/LC-Deployment/actions/build-push-front@main
      with:
        image: "front-end"
        tags: ${{ inputs.tag }}
        type: ${{ inputs.type }}
        ghcr_pat: ${{ secrets.GHCR_PAT }}