name: 'Build push front image'
on:
  workflow_dispatch:
    inputs:
      tags_name:
        description: tag name

jobs:
  build-back-image:
    # needs: install-back-dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/SIT-LightCode/front-end
        tags: |
          ${{ github.event.inputs.tags_name }}
          latest

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
